### ISSUE TITLE
NullPointerException in viatra evm

### ISSUE THREAD

**Issue by TheKorpos** [viatra/v4md#45] opened 2019-11-06 12:00 UTC
Exception trace:

java.lang.NullPointerException
	at org.eclipse.viatra.transformation.evm.specific.event.ViatraQueryEventHandler$1.activationMissing(ViatraQueryEventHandler.java:89)
	at org.eclipse.viatra.transformation.evm.api.event.adapter.EventProcessorAdapter.processEvent(EventProcessorAdapter.java:54)
	at org.eclipse.viatra.transformation.evm.api.event.adapter.EventHandlerAdapter.handleEvent(EventHandlerAdapter.java:62)
	at org.eclipse.viatra.transformation.evm.specific.event.ViatraQueryEventSource.lambda$3(ViatraQueryEventSource.java:81)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.eclipse.viatra.query.runtime.api.impl.BaseMatcher.rawForEachMatch(BaseMatcher.java:222)
	at org.eclipse.viatra.query.runtime.api.impl.BaseMatcher.forEachMatch(BaseMatcher.java:227)
	at org.eclipse.viatra.transformation.evm.specific.event.ViatraQueryEventSource.resendEventsForExistingMatches(ViatraQueryEventSource.java:81)
	at org.eclipse.viatra.transformation.evm.specific.event.ViatraQueryEventSource.beforeHandlerAdded(ViatraQueryEventSource.java:42)
	at org.eclipse.viatra.transformation.evm.api.event.adapter.EventSourceAdapter.addHandler(EventSourceAdapter.java:54)
	at org.eclipse.viatra.transformation.evm.specific.event.ViatraQueryEventHandler.prepareEventHandler(ViatraQueryEventHandler.java:60)
	at org.eclipse.viatra.transformation.evm.specific.event.ViatraQueryRuleInstanceBuilder.prepareRuleInstance(ViatraQueryRuleInstanceBuilder.java:27)
	at org.eclipse.viatra.transformation.evm.api.RuleSpecification.instantiateRule(RuleSpecification.java:94)
	at org.eclipse.viatra.transformation.evm.api.RuleBase.instantiateRule(RuleBase.java:71)
	at org.eclipse.viatra.transformation.evm.api.adapter.AdaptableRuleBase.instantiateRule(AdaptableRuleBase.java:36)
	at org.eclipse.viatra.transformation.evm.api.RuleEngine.addRule(RuleEngine.java:117)
	at org.eclipse.viatra.transformation.runtime.emf.transformation.eventdriven.EventDrivenTransformation$EventDrivenTransformationBuilder.build(EventDrivenTransformation.java:126)
	at com.incquerylabs.incquery.desktop.patternmatching.queryregistry.MDQueryRegistry.<init>(SourceFile:139)
	at com.incquerylabs.incquery.desktop.patternmatching.queryregistry.MDQueryRegistry.getOrCreateRegistry(SourceFile:151)
	at com.incquerylabs.incquery.desktop.IncQueryPlugin$3.projectOpened(SourceFile:137)
	at com.nomagic.magicdraw.core.project.ProjectsManager.fireProjectOpened(ProjectsManager.java:1560)
	at com.nomagic.magicdraw.persistence.ci.f.u.a(u.java:32)
	at com.nomagic.magicdraw.persistence.ci.f.az$e.s(az$e.java:306)
	at com.nomagic.magicdraw.persistence.ci.f.az.x(az.java:469)
	at com.nomagic.magicdraw.persistence.ci.f.az.b(az.java:459)
	at com.nomagic.magicdraw.persistence.ci.f.j.a(j.java:61)
	at com.nomagic.magicdraw.persistence.ci.f.j.a(j.java:75)
	at com.nomagic.magicdraw.persistence.ci.f.j.postOperation(j.java:61)
	at com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService$ComplexEventSupport.notify(DefaultComplexOperationEventService.java:454)
	at com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService$ComplexEventSupport.notify(DefaultComplexOperationEventService.java:1)
	at com.nomagic.ci.event.AbstractEventSupport.fireEvent(AbstractEventSupport.java:130)
	at com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService.createAndDeliverEvent(DefaultComplexOperationEventService.java:92)
	at com.nomagic.ci.persistence.local.internal.d.b.a(b.java:114)
	at com.nomagic.ci.persistence.local.internal.d.b.access$1(b.java:105)
	at com.nomagic.ci.persistence.local.internal.d.b$d.notify(b$d.java:205)
	at com.nomagic.ci.persistence.local.AbstractLocalProjectListener.notify(AbstractLocalProjectListener.java:1)
	at com.nomagic.ci.persistence.local.spi.ProjectEventSupport.notifyListener(ProjectEventSupport.java:66)
	at com.nomagic.ci.persistence.local.spi.ProjectEventSupport.notifyListener(ProjectEventSupport.java:1)
	at com.nomagic.ci.persistence.local.spi.FailureHandleEventSupport.notify(FailureHandleEventSupport.java:20)
	at com.nomagic.ci.persistence.local.spi.FailureHandleEventSupport.notify(FailureHandleEventSupport.java:1)
	at com.nomagic.ci.event.AbstractEventSupport.fireEvent(AbstractEventSupport.java:130)
	at com.nomagic.ci.persistence.local.spi.AbstractProject.fireEvent(AbstractProject.java:2128)
	at com.nomagic.ci.persistence.local.spi.AbstractProject.fireEvent(AbstractProject.java:2118)
	at com.nomagic.ci.persistence.local.spi.AbstractProject.fireEvent(AbstractProject.java:2099)
	at com.nomagic.ci.persistence.local.spi.AbstractPrimaryProject.open(AbstractPrimaryProject.java:236)
	at com.nomagic.ci.persistence.local.spi.localproject.LocalProjectRepository.doOpen(LocalProjectRepository.java:174)
	at com.nomagic.ci.persistence.local.spi.localproject.LocalProjectOpenUtil.doOpenProject(LocalProjectOpenUtil.java:60)
	at com.nomagic.ci.persistence.local.spi.localproject.LocalProjectRepository.doOpenProject(LocalProjectRepository.java:129)
	at com.nomagic.ci.persistence.local.spi.ProjectOpenUtil.doOpenProject(ProjectOpenUtil.java:60)
	at com.nomagic.ci.persistence.local.spi.ProjectOpenUtil.openProject(ProjectOpenUtil.java:44)
	at com.nomagic.ci.persistence.local.spi.DefaultProjectOpenUtil.defaultOpenProject(DefaultProjectOpenUtil.java:50)
	at com.nomagic.ci.persistence.local.spi.DefaultProjectRepository.openProject(DefaultProjectRepository.java:141)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.loadStorage(ProjectLoadService.java:655)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.lambda$doLoad$0(ProjectLoadService.java:411)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.loadWithLoader(ProjectLoadService.java:447)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.doLoad(ProjectLoadService.java:410)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.load(ProjectLoadService.java:281)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.load(ProjectLoadService.java:235)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.loadAndHandleErrors(ProjectLoadService.java:95)
	at com.nomagic.magicdraw.persistence.ProjectLoadService$1.execute(ProjectLoadService.java:175)
	at com.nomagic.task.Task.construct(Task.java:191)
	at com.nomagic.task.SwingWorker$2.call(SwingWorker.java:208)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.nomagic.task.SwingWorker$SwingWorkerFuture.run(SwingWorker.java:594)
	at com.nomagic.task.BackportedThreadPoolExecutor$Worker.runTask(BackportedThreadPoolExecutor.java:1583)
	at com.nomagic.task.BackportedThreadPoolExecutor$Worker.run(BackportedThreadPoolExecutor.java:1614)
	at com.nomagic.task.PooledThread.run(PooledThread.java:64)

MagicDraw Version:
Cameo Systems Modeler 19.0 SP2
Version: Evaluation
Edition: Enterprise
License: Seat
Build: 20190308_2121-7e0c6c3a
Registered to: IncQuery Labs Ltd
Expires at: March 2, 2020

Third Party Plugins:
IncQuery Desktop 1.8.3 (IncQuery Labs Ltd.)
V4MD 2.3.0-SNAPSHOT (IncQuery Labs Ltd.)

**Comment by TheKorpos** [comment] 2019-11-06 12:06
The exception is thrown right away on project open. (IQD is installed)

**Comment by TheKorpos** [comment] 2019-11-06 12:17
![viatrabug](https://user-images.githubusercontent.com/35429470/68297644-c990e780-0097-11ea-8d24-a3ff210ebf01.png)

**Comment by TheKorpos** [comment] 2019-11-06 12:30
![image](https://user-images.githubusercontent.com/35429470/68298424-9fd8c000-0099-11ea-925e-43326943eb0b.png)

**Comment by ujhelyiz** [comment] 2019-11-06 12:59
After a short debugging session, we have found that the issue is caused by the Attribute Monitor initialized too late in the lifecycle, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=552027#c9 Will prepare a fix.

**Comment by ujhelyiz** [comment] 2019-11-06 17:22
Fixed in VIATRA (and V4MD) 2.3.0.M3

**Closed by ujhelyiz** 2019-11-06 17:22 UTC
