### ISSUE TITLE
V4MD hangs on project usage removal

### ISSUE THREAD

**Issue by lunkpeter** [viatra/v4md#37] opened 2019-09-25 16:58 UTC
<img width="1091" alt="Screen Shot 2019-09-25 at 09 47 49" src="https://user-images.githubusercontent.com/3957526/65622048-bf001000-df79-11e9-9e52-569db3875f1a.png">

[Stuck_On_Remove_Project_Usage.nps.zip](https://github.com/viatra/v4md/files/3653784/Stuck_On_Remove_Project_Usage.nps.zip)

**Comment by lunkpeter** [comment] 2019-09-26 18:39
@ujhelyiz I have confirmed on apple infrastructure, after merging #38 the usage removal does not cause any catastrophic errors with MD. We still need to check the status of the index though. please use the internal TWC for testing

**Comment by ujhelyiz** [comment] 2019-09-27 09:59
Some details about the fix and a proposed test scenario:

When adding or removing a project usage (e.g. a profile), the contents of the Base index are to be updated, and in some cases (mostly in case of TWC projects) the existing set of root notifiers have to be updated. In V4MD 2.2.1 the code responsible for this part was updated in a way that (might) result(s) in an infinite loop.

I propose the following test scenario to test whether the proposed fix solves the issue and does not consist of any regressions (to be executed both for local and TWC projects):

1. Have a MagicDraw instance with IncQuery Desktop installed.
2. Create a query definition that lists all instances of a given UML type (e.g. Class, Activity, etc.)
3. Add a new project usage with a project that includes at least a single member of the type specified in the query and **check** whether the query results have changed to include the new member.
4. Remove the previously added project usage and **check** whether the query results have reverted to their original values.

Switching steps 3 and 4 provides a very similar test suite: first, remove a used project that changes the results; then add it back and **check** whether the query results are updated correctly.

My expectations are that the results will be the following:

1. Using **V4MD 2.2.1** and a **file-based project** everything should work as expected.
2. Using **V4MD 2.2.2-SNAPSHOT** and a **file-based project** everything should work as expected.
3. Using **V4MD 2.2.1** and a **TWC project** should result in an infinite loop at step 3.
4. Using **V4MD 2.2.2-SNAPSHOT** and a **TWC project** should work as expected.

When items 2-4 are not met, we should have another go at providing a bugfix or creating a better test scenario.

**Comment by beothy** [comment] 2019-09-30 12:37
I've tested the proposed test scenario by @ujhelyiz.

What I've found is:
**1. Using V4MD 2.2.1 and a file-based project:** Everything is working as expected.
**2. Using V4MD 2.2.2-SNAPSHOT and a file-based project:** Everything is working as expected.
**3. Using V4MD 2.2.1 and a TWC project:** MagicDraw freezes If I add a Profile to the model.
**4. Using V4MD 2.2.2-SNAPSHOT and a TWC project:** Everything is working as expected.

It seems, that 2.2.2-SNAPSHOT solved the freezing issue without functionality regression.

**Comment by lunkpeter** [comment] 2019-10-01 03:35
I got reports that the problem persists on project addition but not on removal. We need to figure out this issue ASAP

**Comment by beothy** [comment] 2019-10-01 08:56
I've added two server project (a smaller and a bigger one) to another server project without any problem. @lunkpeter Are we sure that they used 2.2.2-SNAPSHOT when the addition problem happened?

**Comment by lunkpeter** [comment] 2019-10-01 15:45
Thanks for the update, ill confirm the v4md version today

**Comment by ujhelyiz** [comment] 2019-10-02 15:51
We got feedback in person that the issue is indeed fixed in 2.2.2-SNAPSHOT.

**Closed by ujhelyiz** 2019-10-02 15:51 UTC
Labels: bug
