### ISSUE TITLE
Guava is being added to the MD plugin

### ISSUE THREAD

**Issue by TheKorpos** [viatra/v4md#35] opened 2019-09-23 13:32 UTC
This dependency transitively pulls it in

https://github.com/viatra/v4md/blob/a9d2f10c852fc1f2cf73799301131001e1056a76/com.incquerylabs.v4md/build.gradle#L106

**Comment by ujhelyiz** [comment] 2019-10-07 11:04
Bundled Guava was removed from V4MD for version 2.2.2. Some documentation is still necessary, but it should wait until we have executed some tests.

**Comment by ujhelyiz** [comment] 2019-10-11 08:26
Guava had to be readded, as right now V4MD cannot even initialize a query engine without Guava available on the public classpath. VIATRA runtime has to be cleaned up before this could work.

**Comment by ujhelyiz** [comment] 2019-10-11 08:30
On the VIATRA side, the issue is tracked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=552027 and is aimed to be fixed for 2.3.0, planned to be released December 2019. Of course, the fix will hopefully be available in earlier 2.3 milestones.

**Comment by ujhelyiz** [comment] 2019-11-05 08:46
Latest 2.3.0-SNAPSHOT builds are Guava-free. Closing the issue as fixed.

**Closed by ujhelyiz** 2019-11-05 08:46 UTC
